### ISSUE TITLE
Incorrect field passed (username vs. IP)

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#104]
https://utrs.wmflabs.org/appeal.php?id=16291 while trying to notify admin of request to review.

Notice: Undefined index: by in /usr/UTRSgit/utrs/public_html/src/UTRSBot.class.php on line 71

Notice: Undefined offset: 0 in /usr/LivePeachy/Peachy/Includes/User.php on line 180

Notice: Undefined index: by in /usr/UTRSgit/utrs/public_html/src/UTRSBot.class.php on line 78

Fatal error: Uncaught exception 'BadTitle' with message 'Invalid title: User talk:' in /usr/LivePeachy/Peachy/Includes/Page.php:2053 Stack trace: #0 /usr/LivePeachy/Peachy/Includes/Page.php(304): Page->get_metadata(Array) 
# 1 /usr/LivePeachy/Peachy/Includes/Wiki.php(2448): Page->__construct(Object(Wiki), 'User_talk:', NULL, true, true, NULL)
# 2 /usr/UTRSgit/utrs/public_html/src/UTRSBot.class.php(78): Wiki->initPage('User_talk:')
# 3 /usr/UTRSgit/utrs/public_html/appeal.php(283): UTRSBot->notifyAdmin('Usernamen1', Array)
# 4 {main} thrown in /usr/LivePeachy/Peachy/Includes/Page.php on line 2053

**Comment by Salvidrim** [comment]
I tested with another appeal to see if it was somehow linked to Coffee being the blocking admin

In https://utrs.wmflabs.org/appeal.php?id=16306 the "notify admin" worked correctly for Coffee

**Comment by dqwiki** [comment]
This has been emergency patched to live
