### ISSUE TITLE
CU IP Data

### ISSUE THREAD

**Issue by MikeVwiki** [UTRS/utrs#106]
The most recent requests (since approximately Oct 20) all display the wmf labs IP first and then the IP address of the user requesting an unblock. This results in the system assigning all the users to the same IP (from the wmf labs) when you click on the "Appeals by this IP" button.

**Comment by TParis** [comment]
Fixed with this commit: bb042656049b733437ce5aac9266d4644f63bc01

**Comment by Salvidrim** [comment]
IIRC last time this happened was because the tool's Labs session had ended or something of that ilk. TParis and DQ are the ones with access so they'll have to check it out. :)


~Salv/Ben


________________________________

**Comment by TParis** [comment]
Thanks Mike – it should be fixed now.
