### ISSUE TITLE
Broken "confirmation diff"

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#111]
The "confirmation diff" link in account requests tries to load `https://utrs.wmflabs.org/diff`

Example: account request 248 for RickinBaltimore with diff 753200803 tries to load https://utrs.wmflabs.org/753200803 which is of course a 404 error

**Comment by dqwiki** [comment]
We really could just make them insert the diff number and load that...easier than all this syntax stuff.

**Comment by TParis** [comment]
Someone needs to look at the OAuth solution

**Comment by dqwiki** [comment]
I'm going to crack down on OAuth the next few days, so marking won't fix.
