### ISSUE TITLE
When removing checkuser rights, accounts become disabled.

### ISSUE THREAD

**Issue by TParis** [UTRS/utrs#138]
See https://utrs.wmflabs.org/userMgmt.php?userId=26

**Comment by Salvidrim** [comment]
I remember DQ telling me that we no longer needed to "manually" remove CU flags since it would be auto-updated on next user login.

![image](https://user-images.githubusercontent.com/10283535/28747430-6867377a-746c-11e7-8b3c-387057b25724.png)
