### ISSUE TITLE
Require OAuth for account unblock requests

### ISSUE THREAD

**Issue by JJMC89** [UTRS/utrs#163]
When a user answers Yes to 'Do you have an account on Wikipedia?', they should be required to authenticate with OAuth. The is to prevent others from initiating unblocks for another user's account.

**Comment by Salvidrim** [comment]
This is ultimately a very good idea, but will obviously require non-trivial work from devs when they have time. Thanks for thinking of opening this ticket @JJMC89 !

Leaving a note for posterity that this suggestion is to address abuse such as the multiple bogus unblock requests filed by an LTA on July 17th: [https://en.wikipedia.org/w/index.php?limit=101&title=Special%3AContributions&contribs=user&target=UTRSBot&namespace=&tagfilter=&start=2019-07-17&end=2019-07-17](https://en.wikipedia.org/w/index.php?limit=101&title=Special%3AContributions&contribs=user&target=UTRSBot&namespace=&tagfilter=&start=2019-07-17&end=2019-07-17) from which one of the most visible impacts was coercing UTRSBot to leave talk page messages to the targets of the abuse

**Comment by revi** [comment]
Note that OAuth cannot be used on a project where they are locally blocked. See [E007](https://www.mediawiki.org/wiki/Help:OAuth/Errors#E007).

This means if you are trying to authenticate on enwiki while you are blocked on en — it will fail.
