### ISSUE TITLE
Do not provide link to reply to closed unblock ticket

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#23]
Title says it all.

**Comment by dqwiki** [comment]
Currently through the workflow though they can't. Once an appeal is closed, there is no chance at reply. Hence why I was moving to remove this link as redundant.

**Comment by Salvidrim** [comment]
Ah, sorry! I thought the link actually gave the ability to reply to closed tickets and this was about removing said ability. :p

**Comment by dqwiki** [comment]
Done at fbb362dae85dc940c4c1a025111742d92d512284
