### ISSUE TITLE
Allow a ticket to be returned to the "new" queue

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#24]
For example, a new ticket that is, for some reason, put "ON_HOLD" (maybe by mistake?) and then removed from ON_HOLD and released, will be in the "AWAITING_REVIEWER" queue, even without a reservation, and there is no way at all to return it to the "NEW" queue, which means it might be passed over by other UTRS volunteers as they believe the ticket awaits a reply by the reserving admin, even though the appeal is unreserved.

I guess either there should be a way to re-flag an appeal as "NEW", or appeals should be automatically flagged as "NEW" when they are unreserved and no reply has been sent to the user.

**Comment by Salvidrim** [comment]
For a non-mistake, specific example: Ticket#12464

0.- Appeal created, Status: "NEW"
1.- TParis reserved the appeal, then sent the ticket to CUs, Status: "AWAITING_CHECKUSER"
2.- Callanecc returned it to DQ with a "can't help", Status: "AWAITING_REVIEWER"
3.- DQ released the appeal to open it "to the general population to get [it] moving." 

At this point, the appeal should've been able to be changed back to "NEW", since it was not responded to yet and required a new reviewer.
Instead it lingered the "AWAITING_REVIEWER" queue, where it will be assumed to be reserved and awaiting a specific reviewer's reply, and you won't know it actually unreserved and needs a new reviewer unless you zoom in on it, which isn't immediately obvious.
(Luckily, in this case, I had seen the name on-wiki and had an idea of what to do it with, so I saw it, I personally reserved it a week after DQ released it)

**Comment by Salvidrim** [comment]
I assume DQ tried performing this (via database) on ticket#13122

*Mike V	could a tool admin release this? Thanks
*Mike V	Status change to AWAITING_ADMIN
*DeltaQuad	Released appeal via database (Reset to NEW)
*DeltaQuad	Appeal reservation returned to tool users.
*DeltaQuad	Multiple comments supressed via database (Excessive debugging attempts)

The ticket's status (as of this time) is still "AWAITING_REVIEWER", so I assume the tests were unsuccessful. :(

**Comment by dqwiki** [comment]
No the DB hack was successful. But I just found the need for this...so uping urgency level.

**Comment by dqwiki** [comment]
Fix finished in a122abfc652e1040aaf234f378be47cd9a013d1d
