### ISSUE TITLE
Prevent appeal if talkpage has been revoked onwiki

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#28]
If they've been forced out onwiki, no point in allowing appeals on the tool.

**Comment by Salvidrim** [comment]
Wait, what? Most talk-page-revoked messages (up to and including WP:GAB) actually explain that when talk page access is revoked, the next appeal "step" is UTRS (followed by BASC). That has always seemed like completely standard and accepted procedure.

**Comment by dqwiki** [comment]
Ya, this isn't happening. Disregard.
