### ISSUE TITLE
Username with "!" cannot register

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#29]
This was a while ago (September), but I tried repeatedly to register with my on-wiki username (Salvidrim!), but UTRS did not work. I don't remember the exact results it returned then.

I had to opt for an alternative solution and register using a doppelganger's account name (Salvidrim), which means that using {{adminname}} doesn't return my "real" on-wiki account name (but Salvidrim redirects to Salvidrim! anyways so it's not a big issue).

I dunno if characters other than an exclamation mark would also cause issue but this might warrant further testing since not every potential volunteer have purely alphanumeric user names.

**Comment by Salvidrim** [comment]
There was also an attempt to rename my account, but it was reverted right away, so I assume it caused some issues:

2014-09-04 19:35:02 UTC	TParis renamed user to "Salvidrim!" (Old username: "Salvidrim")
2014-09-04 19:35:07 UTC	TParis renamed user to "Salvidrim" (Old username: "Salvidrim!")

**Comment by dqwiki** [comment]
I've done the rename again. It hasn't broken anything. yet...

I don't think we ever confirmed the bug, would be a good thing to test out on Beta server.

**Comment by Salvidrim** [comment]
We have a Beta server? lol

**Comment by dqwiki** [comment]
Oh yes, utrs.wmflabs.org/beta
