### ISSUE TITLE
List of tool users

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#31]
[[Wikipedia talk:Unblock Ticket Request System#List_of_UTRS_admins]]

**Comment by Salvidrim** [comment]
I don't know if anyone has thought about setting up a "flag" user-right for UTRS-members, as was recently done for OTRS-members? It would probably simplify things significantly in the long run but would require a lot of on-wiki discussion...

**Comment by dqwiki** [comment]
Not sure I see the benefit. The one for OTRS is so that edits could be tracked when they verified images/text permission through a ticket and added the template. What would be our use?

**Comment by Salvidrim** [comment]
Good point, I hadn't realized the OTRS user-right had actual uses beyong categorization and creating an easy way to list all users with access.

**Comment by Chedwiki** [comment]
self identify as UTRS (en-wiki) member: User:Ched
