### ISSUE TITLE
Defer to user

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#35]
Force assignment of case to an admin, and email them about it.

**Comment by Salvidrim** [comment]
With the advent of UTRSBot, leaving a talk page message might be preferable to e-mailing

**Comment by Chedwiki** [comment]
could someone remove me from this stuff - I don't do wiki anymore.  I've
clicked unsubscribe several times, but I'm still getting them.

thanks,
Ched

On Sat, May 7, 2016 at 6:43 PM, Salvidrim <notifications@github.com> wrote:

> With the advent of UTRSBot, leaving a talk page message might be
> preferable to e-mailing
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UTRS/utrs/issues/35#issuecomment-217673461>
>



-- 
____________________________
Ched Davis

**Comment by TParis** [comment]
Ched,

 

It appeals you have the page watched: https://github.com/UTRS/utrs/watchers

 

Go to that URL and click “Unwatch”

 

v/r,
TParis

**Comment by Salvidrim** [comment]
I don’t think I can “forcibly unsubscribe you” from this issue, but when you go https://github.com/UTRS/utrs/issues/35#issuecomment-217673461 and make sure you’re logged in, then you should be able to succesfully unsubcribe. It’ll tell you “you’re ignoring this thread”. :/

~ Benoit / Salvidrim

**Comment by Chedwiki** [comment]
thank you .. best to all.
:-)

ched

On Sat, May 7, 2016 at 11:54 PM, TParis <notifications@github.com> wrote:

> Ched,
>
>
>
> It appeals you have the page watched:
> https://github.com/UTRS/utrs/watchers
>
>
>
> Go to that URL and click “Unwatch”
>
>
>
> v/r,
> TParis
>
>
>
> From: Ched [mailto:notifications@github.com]
> Sent: Saturday, May 7, 2016 5:48 PM
> To: UTRS/utrs <utrs@noreply.github.com>
> Subject: Re: [UTRS/utrs] Defer to user (#35)
>
>
>
> could someone remove me from this stuff - I don't do wiki anymore. I've
> clicked unsubscribe several times, but I'm still getting them.
>
> thanks,
> Ched
>
> On Sat, May 7, 2016 at 6:43 PM, Salvidrim <notifications@github.com
> <mailto:notifications@github.com> > wrote:
>
> > With the advent of UTRSBot, leaving a talk page message might be
> > preferable to e-mailing
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/UTRS/utrs/issues/35#issuecomment-217673461>
> >
>
>
>
> --
> ____________________________
> Ched Davis
>
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <
> https://github.com/UTRS/utrs/issues/35#issuecomment-217689686> <
> https://github.com/notifications/beacon/ABU1nWCwBYT84GQDatXoOwu9dRgHujF8ks5p_Vz1gaJpZM4DneH_.gif>
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/UTRS/utrs/issues/35#issuecomment-217689841>
>



-- 
____________________________
Ched Davis

**Comment by dqwiki** [comment]
#69 is definitely a better implementation of this. Closing.
