### ISSUE TITLE
Having correct "Blocking admin" names

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#40]
When a user files a ticket and makes a mistake in their usernames, I know it is currently possible to change the username linked with an appeal via the database for tooldevs, but some measure of control could be granted to tooladmins, to fix, for example:

*Usernames
*Blocking admin name

**Comment by dqwiki** [comment]
With the denying on username mismatch, is it still an issue? The only possible instance I can see is a capitalization issue.

As for blocking admin name, in the future, we may just extract that from the API, extending on the check block function. That will take some time to work on though.

**Comment by Salvidrim** [comment]
The username issue itself is now fixed/obsoleted since users can only appeal when the username matches the blocked user account.

The issue remains with blocking admin names, because right now the userpage link relies on the data submitted by the appellant, which can be anything (see appeal#14660), so we should either be able to fix it manually, or grab it from the API

**Comment by Salvidrim** [comment]
See https://en.wikipedia.org/wiki/Wikipedia:Bots/Requests_for_approval/UTRSBot for additional discussion on why having the "blocking admin" field rely entirely on appellant-submitted text is less than ideal:

**Comment by dqwiki** [comment]
I've requested that #69 address this directly as it already has the code set up for it.
