### ISSUE TITLE
Fatal error when previewing response

### ISSUE THREAD

**Issue by nakon** [UTRS/utrs#41]
On https://utrs.wmflabs.org/sendEmail.php?id=13393&close=1 when previewing my response:

Fatal error: Call to a member function getName() on a non-object in /usr/UTRSgit/utrs/public_html/sendEmail.php on line 207

**Comment by Salvidrim** [comment]
I tried reopening the same appeal and could not replicate the issue. Did you encounter de same error on another ticket?

**Comment by nakon** [comment]
Yes, I can replicate this on every ticket.
https://utrs.wmflabs.org/sendEmail.php?id=13380&close=0

Fatal error: Call to a member function getName() on a non-object in /usr/UTRSgit/utrs/public_html/sendEmail.php on line 207

It's probably because of the lowercase in my username, I also had a difficulty in signing up because of it.

**Comment by Salvidrim** [comment]
I’ve just tried to rename your account to “Nakon” (couldn’t rename directly so I renamed to “nakon2” then “Nakon”.
Is there still an issue?

If it works now, this may be linked to the other open ticket about “!” in a username, where I’ve had trouble signing in (haven’t had time to test it out yet)

~ Benoit / Salvidrim

**Comment by nakon** [comment]
Unfortunately, this is still showing up.  I've logged out and back in to kill my session. It doesn't really break anything but it just doesn't let me submit from the preview page.

Fatal error: Call to a member function getName() on a non-object in /usr/UTRSgit/utrs/public_html/sendEmail.php on line 207

**Comment by dqwiki** [comment]
The function that is being called relates to the template you are trying to
use. At least thats what face value says...but its 1am so i could be wrong.
Just for further debug, which template are you trying to use?

DeltaQuad - Mobile
UTRS Dev

**Comment by nakon** [comment]
This occurs on every template when previewing the message.

**Comment by dqwiki** [comment]
Confirmed this on beta. Looking into it.

**Comment by dqwiki** [comment]
sendEmail.php#L209 does not pass the $tid into the url, which exists on the initial call of the page. Should be a simple fix similiar to sitenotice.php#L36

**Comment by lfaraone** [comment]
FWIW, this is still happening on the deployed site.

**Comment by Salvidrim** [comment]
I'm speaking with DQ and we're finally working this bug out, which brought this hilarious log entry:

![untitled](https://cloud.githubusercontent.com/assets/10283535/11322408/31d9cf68-90b8-11e5-8acc-335f594d6068.png)
