### ISSUE TITLE
Deal with account requests that are not to be approved

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#43]
For example, when a non-admin requests an account, or any other circnumstance where an account request is made (thus added to the "unapproved accounts" list"), but the decision is to NOT approve it. 

At the present time, there is no way to remove it from the "unapproved accounts" list (short of approve it without activating it, which gives the wrong idea).

Perhaps we could add a "declined" option if we want to keep these accounts existing for some technical reasons (maybe to avoid breaking the numbering order?)

Or if at all feasible, a way to delete accounts could be welcome. Perhaps deletion could be some "deactivation" that makes the account not listed anywhere although it continues existing in the database (so as to not break attribution of tickets and whatnot).

**Comment by dqwiki** [comment]
I just looked at the DB, the only way to deal with this in the current software is to mark it approved but not active, which will deny access anyway. Definitely something to be worked out.

**Comment by Salvidrim** [comment]
I just did that, and renamed it
        to "Mwaldeck-unapproved" for the sake of clarity, until there is
        something better to do with it, and to set it apart from
        "retired" users.

**Comment by Salvidrim** [comment]
Another reason why the "approve but not activate" solution is, at best, terrible: doing that generates an e-mail to the user:

=============================

From: UTRS Development Team <unblock@toolserver.org>
Date: Mon, Nov 16, 2015 at 8:13 AM
Subject: UTRS account approved
To: kyle.bryant@students.wmcsd.org


Hello Kylenator21, This is a notification that your account has been approved on the Unblock Ticket Request System (UTRS) by Salvidrim!. Please login to the system to begin reviewing unblock requests. Thanks for volunteering!

**Comment by dqwiki** [comment]
Right now I feel like #34 is a blocker for this, because any real implementation would redesign the access levels that are used on the tools. So sadly, this is stalled out right now.

**Comment by Salvidrim** [comment]
For the record such account requests are still coming in regularly, but to avoid the above issues, I simply rename them to "unapproved" and let the account requests sit there, unresponded to.

**Comment by dqwiki** [comment]
Added oversight hack, which eventually should be turned into a function of the tool

**Comment by Salvidrim** [comment]
Can be closed as obsoleted by OAuth since we will never have "unauthorized account requests" anymore, and any that we had received pre-OAuth have been oversighted away.
