### ISSUE TITLE
"Blocked IP" tickets can't be created

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#45]
I noticed that, as far as I can see, we haven't received a single UTRS ticket for blocked IPs since DQ implemented the "check if blocked" system as part of ticket creation... and now we've had a few reports of people being unable to post appeals from blocked IPs.

This is something we can't really test ourselves because our own IPs are not blocked.

**Comment by Salvidrim** [comment]
I'll add some previous exchange on the topic:

**Comment by dqwiki** [comment]
The API doesn't handle list=users with IP addresses. I originally had issues using the list=blocks. List blocks should work with IPs. Testing now. To be clear, Username checks use list=users, IPs use list=blocks.

**Comment by dqwiki** [comment]
It works now. Unfortunately I have to partial deploy parts of #42 to send this live immediately. So that may introduce new bugs. Keep an eye on this.

**Comment by dqwiki** [comment]
As a follow up to this, Appeals by IP hardblocked accounts can't be accepted. Now making that attempt. Also removing and fixing the where to get help creating an account.

**Comment by Salvidrim** [comment]
Also, I've just added a sitenotice advising users and responders that:

"Users whose account is not directly blocked but who are affected by a block or rangeblock of their IP address cannot currently appeal through the UTRS interface. This is a known issue and we are working on it. In the meantime, an e-mail can be sent to utrs-admins@googlegroups.com where a tooladmin will process the appeal manually."

**Comment by dqwiki** [comment]
I've tested this on alpha before merging, It's good to go.
