### ISSUE TITLE
Gathering info on rejected appeal attempts

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#46]
From: "Benoit Landry"
Date: Jun 22, 2015 7:00 PM

Do you get some sort of data on attempts to file appeals that are rejected before a ticket is created? 

=========================================

From: DeltaQuad Wikipedia 
Sent: Friday, June 26, 2015 8:05 PM

Salvidrim: To answer your last question, no. It might be worthwhile...im not sure. Put it in github as a question and we'll discuss specifics there.

**Comment by Salvidrim** [comment]
It'd probably be more useful to troubleshoot the tool than in actual usage

**Comment by dqwiki** [comment]
My concern with this is that the database, or whatever log file would be excessively large and oversized, being a nightmare to search to begin with. There are really enough ways to trick the system to test a certain function if needed (I can explain by email if you wish). With that, I don't really see a point to this.
