### ISSUE TITLE
Request appeal language before launching appeal form

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#47]
With the starting of internationalization, login sessions only apply to wiki admins and not appellants. Because the index page has internationalized statements, we need to be able to have them select a language before getting the form. Most likely it will be a regular page that then redirects to a file appeal page.

**Comment by Salvidrim** [comment]
Could we default by pulling the browser language (and offer options to change language) like most "big players" do?
~Benoit / Salvidrim
[Sent from my Nexus 5]

**Comment by dqwiki** [comment]
We could have a ptwiki user who edits enwiki, and then gets blocked on enwiki and tries to appeal with ptwiki not understanding (or god forbid) seeing it. We are also then vulnerable to XSS attacks as we would be using the UA (which might not even contain the language) or the IP address (which is sometimes way off anyway.

Forcing them to purposefully decide which wiki they want to appeal with esp if we expand beyond ptwiki (say commons) is going to be a better option.

**Comment by dqwiki** [comment]
I think this might be better to hold in user and then call it from User::getLangSetting() or something. All pages already call user of some sort.

**Comment by dqwiki** [comment]
This was done a lot better by forcing a redirect if a language cookie wasn't set while loading any public page. The user then has the option to set the language and an option to modify it.
