### ISSUE TITLE
Prevent non-admins from requesting accounts

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#51]
We've recently had a large number of non-admins and/or blocked accounts requesting UTRS accounts, which (due to #43) I've had to "approve" but not "activate" and then rename to "[username]-unapproved". Is there a way we could query on-wiki user-right status to disallow UTRS account requests from non-admins?

Perhaps #50 would automatically make this issue obsolete, but I'm still opening this because if resolving #50 is determined to be a longer-term project due to its complexity, perhaps this would be a simpler patch in the meantime.

**Comment by dqwiki** [comment]
#50 is the best way of dealing with this, otherwise it's querying the API for a user's admin status.
