### ISSUE TITLE
Redirecting port 80 traffic to 443

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#53]
From: DeltaQuad Wikipedia 
Sent: Saturday, November 21, 2015 5:27 AM
To: Benoit Landry 
Subject: Re: [UTRS Devs] FW: [UTRS Admin] utrs privacy

If it's certified, then I have no issue with it. I just have to find a way to wind it around to port 443. Can you bug this up?

Amanda - DeltaQuad
English Wikipedia Arbitrator
_______________________________________________

On 18 November 2015 at 22:39, Benoit Landrywrote:

This is what I get from home:
![cid_inlineimage0](https://cloud.githubusercontent.com/assets/10283535/11319550/f1ab041c-9048-11e5-8596-681b5da97f3d.png)

When I click on “certificate information” I get a lot of data, lemme know if that’s what you need

~ Benoit / Salvidrim
______________________________________________
From: DQ
Date: Fri, 13 Nov 2015 00:53:27 -0500
Subject: Re: [UTRS Devs] FW: [UTRS Admin] utrs privacy

Can you copy paste me or give me details of the certificate on the HTTPS connection? cause I feel like my antivirus is certifying the domain automatically...

Amanda - DeltaQuad
English Wikipedia Arbitrator
_______________________________________
On 12 November 2015 at 11:01, Ben Salvidrim wrote:

I'm forwarding this to our developper team (which starts and ends with DQ currently). :)

~Ben/Salv
______________________________________________
To: utrs-admins@googlegroups.com
From: NE Ent
Subject: [UTRS Admin] utrs privacy
Date: Thu, 12 Nov 2015 06:29:53 -0500 

En-wikipedia has gone to serving everything https:// (port 443) for privacy reasons, and https://utrs.wmflabs.org/ works. Recommend redirecting port 80 traffic to 443, unless there's some reason not to?

**Comment by dqwiki** [comment]
We have the ability to do this, and i've gotten details on how, I just am awaiting more specific instructions on how to set it up on our labs instance.

**Comment by dqwiki** [comment]
I have the details, just need to work them in.
