### ISSUE TITLE
Encoding issues vs. chinese characters

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#58]
There is at least on area that is affected by encoding issues of chinese characters: running the "permissions check" says Yamaguchi isn't an admin because their Wikipedia account is "User:Yamaguchi先生".

Maybe there are other areas affected by this encoding issues that are worth looking into/testing:

Appellant account names for the purpose of detecting if blocked?
Potential complications with OAuth implementation?
Are there issues with other non-latin scripts?

**Comment by Salvidrim** [comment]
This is no longer a question, the bug is confirmed for the "permissions check" script: it "breaks" when trying to check for User:Yamaguchi先生 and any subsequent users (in order of account number), so later additions (Coffee, Philippe) also show up as "unverified". In theory this might be obsoleted by OAuth when and if that is implemented.

I've decided to leave the question tag so that we remember to check the other questions in the opening comment

**Comment by dqwiki** [comment]
ugh, i've made it worse on the live version. too much work to change and fight with tonight though.

**Comment by Salvidrim** [comment]
![image](https://cloud.githubusercontent.com/assets/10283535/15417499/8688c4a2-1e24-11e6-8ed7-684b3c4cfa70.png)


> Notice: Undefined index: groups in /usr/UTRSgit/utrs/public_html/src/statsLib.php on line 362

> Warning: in_array() expects parameter 2 to be array, null given in /usr/UTRSgit/utrs/public_html/src/statsLib.php on line 362

**Comment by Salvidrim** [comment]
![image](https://cloud.githubusercontent.com/assets/10283535/15417510/b5bf0376-1e24-11e6-84a4-a5f217cc33b1.png)


> Notice: Undefined index: groups in /usr/UTRSgit/utrs/public_html/src/statsLib.php on line 362

> Warning: in_array() expects parameter 2 to be array, null given in /usr/UTRSgit/utrs/public_html/src/statsLib.php on line 362
