### ISSUE TITLE
Tool Internationalization - Translator's thread

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#67]
This bug issue will be to track all requests for language translation and @UTRS/translators will be pinged when new translations are needed. When there are no more items to translate, the issue will be closed. When new translation requests surface, this bug will be reopened.

Translation Team: @dqwiki

Internationalization file: https://github.com/UTRS/utrs/edit/tool-internationalization/public_html/src/messages.php

**Comment by TParis** [comment]
UTRSBot, the Wiki version, uses three templates: Unblock-utrs, Unblock-UTRS-AdminNotify, and UTRS-OPP.

**Comment by dqwiki** [comment]
@Le0nsaud Please accept the invitation to join the team at https://github.com/UTRS and then edit the file linked directly. Currently you have branched off, and that will cause issues on keeping the files up to date. Thank you for helping :D

**Comment by dqwiki** [comment]
New messages are ready for translation.

**Comment by dqwiki** [comment]
We are now sitting at 50 messages for translation, most of them new from index.php. Once this is finished, I should be able to give you a view of what the appeal form will look like.

Also still awaiting for RadiX to accept the invitation to the project.

@LTeles @Le0nsaud You can ask any questions you have about translation here or on my talkpage and @Salvidrim should get back to you, and if he can't figure it out, he'll pass it on to us.

**Comment by dqwiki** [comment]
Closing for preference on v2.
