### ISSUE TITLE
UTRS bot's "admin notif" could mention the reviewer

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#72]
_I've been trying to figure out a shorter title for the issue without success..._

When UTRS leaves a notification to the blocking admin at the UTRS reviewer's request, it should mention who the requesting reviewer is.

The template message says (example: https://en.wikipedia.org/wiki/User_talk:Jpgordon#UTRS_Ticket:_15774) that if the blocking admin does not have or want a UTRS account, they can "respond here", but because it's UTRSBot who leaves the message, the talk page isn't added to the UTRS reviewer's watchlist, and the blocking admin can't know who to ping in their reply.

**Comment by Salvidrim** [comment]
For even more functionality, it could copy the reviewer's last note in the appeal to the talk page message left (such as in the example above, it could post TParis' question to JPGordon's talk page), but I'm not sure how feasible/desirable that would be

**Comment by TParis** [comment]
I had the same idea.   But I'd like it better if we prompted the reviewer on utrs for an on-wiki message rather than assume the last log entry is meant for them. 


Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by TParis** [comment]
I think 8b44dd79f17b1a523139378c5026672afb3127a9 should do that for you.
