### ISSUE TITLE
Add warning if too much text in appeal's fields

### ISSUE THREAD

**Issue by Salvidrim** [UTRS/utrs#75]
Example: appeal 15811

Two of the appeal's text field had more content entered by the appellant than the system allows (I assume it's a character count), but AFAIK there is no warning to the appellant. We should either configure the text field to disallow text entry past the character limit (ideally by blocking input after a threshold or by disallowing submission of the appeal while text fields are too big), or add a warning that there is more text that the software allow and that it will be truncated.

**Comment by dqwiki** [comment]
Verified that this is an interface limitation and not a user input issue.

**Comment by TParis** [comment]
It’s a “these id’s don’t exist on alpha” error.  You can’t run that tool on alpha because the alpha database won’t match the user ids in the on-wiki category.

**Comment by dqwiki** [comment]
I've done what I can for now on too-much-text. Still getting the same error though @TParis  even with the latest solution

http://i.imgur.com/cxPxYa8.jpg

**Comment by dqwiki** [comment]
I just realized that this is only a partial fix and needs to be done to all input on the interface... *sigh*
