### ISSUE TITLE
No blocking admin for initial reply

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#81]
Fatal error: Call to a member function replyNotify() on a non-object in /usr/BETAgit/utrs/public_html/ reply.php  on line 89

No blocking admin exists which is trying to be thrown into the function, and it's throwing up. Replies need to be prevented before the point of assignment.

**Comment by Salvidrim** [comment]
This was discovered while looking at 15839 where the user replied to the appeal before any tool user had reserved it
