### ISSUE TITLE
PHP error when attempting to view Ban Management without sufficient access

### ISSUE THREAD

**Issue by TheLlamaLover** [UTRS/utrs#99]
When clicking on Ban Management (and possibly other pages), a PHP notice pops up relating to banMgmt.php.

Screenshot:
![utrserrormessage](https://cloud.githubusercontent.com/assets/230753/16499227/0b878ab0-3ec5-11e6-9454-1a64af64e7f1.PNG)

**Comment by Salvidrim** [comment]
There are places where I know there are "ban management" functions:

- On the tool administration page (https://utrs.wmflabs.org/userMgmt.php) which shouldn't be in the NavBar for non-tooladmins
- At the bottom of appeals, under the appeal log; but these buttons shouldn't appear for non-tooladmins?

@TheLlamaLover can you tell me where you're trying to access Ban Management from? While the error handling message could, of course, be improved, non-tooladmins simply shouldn't be able to attempt accessing Ban Management at all from within the interface, at that's what looks like the real bug to me.
